# 配置文件
# cookie 以实际获取为准，如遇到带双引号的需用 \ 转义，或改为单引号，或将最外层双引号改为单引号
# e.g.1 cookie = "xxx; app_param={\"brand\":\"iPhone\"}"
# e.g.2 cookie = "xxx; app_param={'brand':'iPhone'}"
# e.g.3 cookie = 'xxx; app_param={"brand":"iPhone"}'

# 青龙随机定时
QL_RANDOM_TIME = false


# CSDN【WEB】
# https://www.csdn.net cookie
[[CSDN]]
cookie = "uuid_tt_dd=xxxxxx; _ga=xxxxxx; UserName=xxxxxx; UserInfo=xxxxxx; UserToken=xxxxxx; UserNick=xxxxxx; AU=768; UN=xxxxxx; BT=xxxxxx; p_uid=xxxxxx; Hm_up_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx; Hm_ct_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx dc_sid=xxxxxx; c_segment=xxxxxx; dc_session_id=xxxxxx; csrfToken=xxxxxx; c_first_ref=xxxxxx; c_first_page=xxxxxx; c_page_id=xxxxxx; announcement-new=xxxxxx; log_Id_click=xxxxxx; c_pref=xxxxxx; c_ref=xxxxxx; dc_tos=xxxxxx; log_Id_pv=xxxxxx; log_Id_view=xxxxxx"

# Freenom
# https://www.freenom.com
[[FREENOM]]
password = ""
username = ""

# 海底捞会员【小程序】
# 抓包访问小程序，thirdCommLogin 中的 openid 及 uid
[[HAIDILAO]]
openid = ""
uid = ""

# 网易云音乐
[[MUSIC163]]
password = ""
phone = ""

# 吾爱破解【WEB】
# https://www.52pojie.cn cookie
[[POJIE]]
cookie = "htVC_2132_connect_is_bind=0; htVC_2132_nofavfid=1; htVC_2132_saltkey=nn8ky0Wy; htVC_2132_lastvisit=1645667308; KF4=LbZAgY; htVC_2132_smile=1D1; htVC_2132_visitedfid=65D16D8D74; Hm_lvt_46d556462595ed05e05f009cdafff31a=1645800993,1646035002,1646053682,1646385987; htVC_2132_con_request_uri=https%3A%2F%2Fwww.52pojie.cn%2Fconnect.php%3Fmod%3Dlogin%26op%3Dcallback%26referer%3Dhttps%253A%252F%252Fwww.52pojie.cn%252F; htVC_2132_seccodecS=103531.217b0c23a95c279303; htVC_2132_seccodecSnIq=103532.ead423fa165988fe08; htVC_2132_auth=df49M41M%2FpXVv3QVt4Hc84siaGC5P1Gi6OphCmPLj6fQlS19mKyylKpdFNMyarR7vi0dGYOgZ82JKwctgYG%2BRWb7yM5b; htVC_2132_lip=58.213.140.66%2C1646385986; htVC_2132_sid=0; htVC_2132_noticonf=1475461D1D3_3_1; htVC_2132_ttask=1475461%7C20220304; htVC_2132_ulastactivity=1646470115%7C0; htVC_2132_lastact=1646470115%09home.php%09spacecp; htVC_2132_checkpm=1; htVC_2132_lastcheckfeed=1475461%7C1646470115; Hm_lpvt_46d556462595ed05e05f009cdafff31a=1646470132"

# 什么值得买
# https://www.smzdm.com cookie
[[SMZDM]]
cookie = "sess=xxxxxx;"

# 微博【APP】
# 微博 APP 抓取开头为 https://api.weibo.cn/2/users/show? 的整个 url 填入即可
[[WEIBO]]
url = "https://api.weibo.cn/2/users/show?wm=3333_2001&launchid=default&b=0&from=10C7193010&c=iphone&networktype=wifi&v_p=90&skin=default&v_f=1&lang=zh_CN&sflag=1&ua=iPhone11,8__weibo__12.7.1__iphone__os15.5&ft=11&aid=01A6z7vnMY53vV2RmackcweDOL1kb8mhhLa7I7hdu1C--f0_4.&get_teenager=1&has_extend=1&uid=3169400273&s=999F42A5&gsid=_2A25P1fm8DeRxGeVP7VsV8C7OzD-IHXVqwwp0rDV6PUJbkdAKLWrxkWpNTVMabHw674nbdbfkXdumUWcMhpdS7zA7&has_profile=1&ul_sid=9F853D1B-062D-453A-8F26-489B62D07E56&ul_hid=9F853D1B-062D-453A-8F26-489B62D07E56&ul_ctime=1657948768442"


# 顺丰速递【APP】
# 顺丰速递 APP自行签到一次，抓取 https://mcs-mimp-web.sf-express.com/mcs-mimp/integralTaskSignService/automaticSignFetchPackage 查看cookie中sessionId
[[SFexpress]]
sessionId = ""