# 配置文件
# cookie 以实际获取为准，如遇到带双引号的需用 \ 转义，或改为单引号，或将最外层双引号改为单引号
# e.g.1 cookie = "xxx; app_param={\"brand\":\"iPhone\"}"
# e.g.2 cookie = "xxx; app_param={'brand':'iPhone'}"
# e.g.3 cookie = 'xxx; app_param={"brand":"iPhone"}'

# 青龙随机定时
QL_RANDOM_TIME = false

# Bilibili【WEB】
#天选时刻 奖品详情
# https://www.bilibili.com cookie
[[BILIBILI]]
cookie = "_uuid=xxxxxx; rpdid=xxx'xxx; LIVE_BUVID=xxxxxx; PVID=xxxxxx; blackside_state=xxxxxx; CURRENT_FNVAL=xxxxxx; buvid3=xxxxxx; fingerprint3=xxxxxx; fingerprint=xxxxxx; buivd_fp=xxxxxx; buvid_fp_plain=xxxxxx; DedeUserID=xxxxxx; DedeUserID__ckMd5=xxxxxx; SESSDATA=xxxxxx; bili_jct=xxxxxx; bsource=xxxxxx; finger=xxxxxx; fingerprint_s=xxxxxx;"

# CSDN【WEB】
# https://www.csdn.net cookie
[[CSDN]]
cookie = "uuid_tt_dd=xxxxxx; _ga=xxxxxx; UserName=xxxxxx; UserInfo=xxxxxx; UserToken=xxxxxx; UserNick=xxxxxx; AU=768; UN=xxxxxx; BT=xxxxxx; p_uid=xxxxxx; Hm_up_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx; Hm_ct_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx dc_sid=xxxxxx; c_segment=xxxxxx; dc_session_id=xxxxxx; csrfToken=xxxxxx; c_first_ref=xxxxxx; c_first_page=xxxxxx; c_page_id=xxxxxx; announcement-new=xxxxxx; log_Id_click=xxxxxx; c_pref=xxxxxx; c_ref=xxxxxx; dc_tos=xxxxxx; log_Id_pv=xxxxxx; log_Id_view=xxxxxx"

# Freenom
# https://www.freenom.com
[[FREENOM]]
password = ""
username = ""

# 海底捞会员【小程序】
# 抓包访问小程序，thirdCommLogin 中的 openid 及 uid
[[HAIDILAO]]
openid = ""
uid = ""

#金典有机奶【小程序】
#金典有机奶 抓包jdshop.yili.com/api/中任意一个accesstoken
[[SATINE]]
accessToken = ""

# 网易云音乐
[[MUSIC163]]
password = ""
phone = ""

#RIO鸡尾酒【小程序】
#RIO鸡尾酒 小程序抓取 https://club.rioalc.com/api/miniprogram/user-info 查看headers中Authorization
[[RIO]]
Authorization = "Bearer xxxxxxx"

# 顺丰速递【APP】
# 顺丰速递 APP自行签到一次，抓取 https://mcs-mimp-web.sf-express.com/mcs-mimp/integralTaskSignService/automaticSignFetchPackage 查看cookie中sessionId
[[SFexpress]]
sessionId = ""

#特步【小程序】
#抓取 wxa-tp.ezrpro.com 域名的包 , ezr-vuid , ezr-st , ezr-ss , ezr-userid 是 headers 中的参数
[[Tebu]]
ezr-vuid = "  "
ezr-st = "  "
ezr-ss = "  "
ezr-userid = "  "

# 什么值得买
# https://www.smzdm.com cookie
[[SMZDM]]
cookie = "sess=xxxxxx;"

# 微博【APP】
# 微博 APP 抓取开头为 https://api.weibo.cn/2/users/show? 的整个 url 填入即可,cookie抓网页和app均可 https://luck.sc.weibo.com/aj/jifen/info
[[WEIBO]]
url = "https://api.weibo.cn/2/users/show?xxxxxxxxxxxxxx"
cookie = ""

# 吾爱破解【WEB】
# https://www.52pojie.cn cookie
[[POJIE]]
cookie = "htVD_2132_client_token=xxxxxx; htVD_2132_connect_is_bind=xxxxxx; htVD_2132_connect_uin=xxxxxx; htVD_2132_nofavfid=xxxxxx; htVD_2132_smile=xxxxxx; Hm_lvt_46d556462595ed05e05f009cdafff31a=xxxxxx; htVD_2132_saltkey=xxxxxx; htVD_2132_lastvisit=xxxxxx; htVD_2132_client_created=xxxxxx; htVD_2132_auth=xxxxxx; htVD_2132_connect_login=xxxxxx; htVD_2132_home_diymode=xxxxxx; htVD_2132_visitedfid=xxxxxx; htVD_2132_viewid=xxxxxx; KF4=xxxxxx; htVD_2132_st_p=xxxxxx; htVD_2132_lastcheckfeed=xxxxxx; htVD_2132_sid=xxxxxx; htVD_2132_ulastactivity=xxxxxx; htVD_2132_noticeTitle=xxxxxx;"